id = "crimson-theme"
name = "Crimson Theme"
version = "0.0.2"
schema_version = 1
authors = ["Kaem Viotto <kaemviotto@icloud.com>"]
description = "A theme inspired by the t3.chat redesign colour scheme."
repository = "https://github.com/kaem-e/zed-crimson-theme"
